# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Use pen name,not real name', max_length=70),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite?'),
        ),
    ]
